### PR TITLE
Upgrade babel to version 7

### PR DESCRIPTION
**Pull request by realityking**
No functional difference but it generates somewhat nicer unminified code.

### CODE REVIEW

**Comment by avoidwork** [comment]
thanks!

**Comment by avoidwork** [comment]
Going to have to force push it out:

```
Running "babili" task
Warning: Cannot find module 'babel-core'
Require stack:
- C:\Users\jason\Projects\filesize.js\Gruntfile.js
- C:\Users\jason\Projects\filesize.js\node_modules\grunt\lib\grunt\task.js
- C:\Users\jason\Projects\filesize.js\node_modules\grunt\lib\grunt.js
- C:\Users\jason\Projects\filesize.js\node_modules\grunt-cli\bin\grunt
- C:\Users\jason\Projects\filesize.js\node_modules\grunt\bin\grunt Use --force to continue.
```

This project needs a toolchain update that isn't going to break it for a large user base :(

**Comment by avoidwork** [comment]
Re-adding comment.

Had to force push it out due to:

```
Running "babili" task
Warning: Cannot find module 'babel-core'
Require stack:
- C:\Users\jason\Projects\filesize.js\Gruntfile.js
- C:\Users\jason\Projects\filesize.js\node_modules\grunt\lib\grunt\task.js
- C:\Users\jason\Projects\filesize.js\node_modules\grunt\lib\grunt.js
- C:\Users\jason\Projects\filesize.js\node_modules\grunt-cli\bin\grunt
- C:\Users\jason\Projects\filesize.js\node_modules\grunt\bin\grunt Use --force to continue.

Aborted due to warnings.
```

This project needs a tool chain update.

**Comment by realityking** [comment]
Oh damn, sorry about that. I do have another PR almost ready to use rollup as the build system. I'll make this commit part of that branch.

**Pull request merged**
