### PR TITLE
refactor: use tsdx

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Comment by avoidwork** [comment]
why?

**Comment by bluelovers** [comment]
allow


```ts
// for cjs by typescript and mjs
import filesize from "filesize";
// old style
const filesize = require('filesize');
const filesize = require('filesize').default;
```

**Comment by avoidwork** [comment]
10 intentionally moved to a named export, why can't you `import {filesize} from "filesize"`?

**Comment by bluelovers** [comment]
because when use esm, we can't use name import from cjs file

that make `import { xxx } from "xxx"` this syntax is not safe when we don't know it is cjs or esm

so keep `import xxx from "xxx"` this syntax is better

**Comment by avoidwork** [comment]
> because when use esm, we can't use name import from cjs file

i don't see how that's possible, but...

```
import assert from "node:assert";
import {filesize, partial} from "../dist/filesize.cjs";
```

^ make that change in the test file and retry.

**Pull request closed without merging**
